version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    links:
      - "mysql:db"
    volumes:
      - /sessions
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: mysql:3306
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - mysql
    image: wordpress:4.8.0-php7.0-apache
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    links:
      - mysql
    ports:
      - "3000:80"
    restart: always
    environment:
      WORDPRESS_ENV: development
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
